name: MolGAN
channels:
  - rdkit
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.9.0=py36_0
  - appnope=0.1.0=py36h9f0ad1d_1001
  - astor=0.7.1=py_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=1.5.0=py36_0
  - brotlipy=0.7.0=py36h37b9a7d_1000
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.15.0=h01d97ff_1001
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - cffi=1.11.5=py36_0
  - chardet=3.0.4=py36h9f0ad1d_1006
  - cryptography=2.9.2=py36hc9d8292_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36h9f0ad1d_1001
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - gast=0.3.3=py_0
  - gettext=0.19.8.1=hb0f4f8b_2
  - glib=2.63.1=h70d4741_1
  - grpcio=1.23.0=py36h7c1f37e_1
  - html5lib=0.9999999=py36_0
  - icu=58.2=h0a44026_3
  - idna=2.9=py_1
  - importlib-metadata=1.6.0=py36h9f0ad1d_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2019.4=233
  - ipykernel=5.3.0=py36h95af2a2_0
  - ipython=7.14.0=py36h9f0ad1d_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.0=py36h9f0ad1d_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - joblib=0.15.1=py_0
  - jpeg=9b=he5867d9_2
  - json5=0.9.0=py_0
  - jsonschema=3.2.0=py36h9f0ad1d_1
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py36h9f0ad1d_1
  - jupyterlab=2.1.2=py_0
  - jupyterlab_server=1.1.4=py_0
  - libboost=1.67.0=hebc422b_4
  - libcxx=10.0.0=1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.3=h0a44026_1
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.11.4=hd174df1_0
  - libsodium=1.0.17=h01d97ff_0
  - libtiff=4.1.0=hcb84e12_0
  - libxml2=2.9.9=hf6e021a_1
  - llvm-openmp=10.0.0=h28b9765_0
  - markdown=3.2.2=py_0
  - markupsafe=1.1.1=py36h37b9a7d_1
  - mistune=0.8.4=py36h37b9a7d_1001
  - mkl=2019.4=233
  - mkl-service=2.3.0=py36hfbe908c_0
  - mkl_fft=1.0.15=py36h5e564d8_0
  - mkl_random=1.1.0=py36ha771720_0
  - nbconvert=5.6.1=py36h9f0ad1d_1
  - nbformat=5.0.6=py_0
  - ncurses=6.2=h0a44026_1
  - notebook=6.0.3=py36h9f0ad1d_0
  - numpy=1.18.1=py36h7241aed_0
  - numpy-base=1.18.1=py36h3304bdc_1
  - olefile=0.46=py36_0
  - openssl=1.1.1g=h0b31af3_0
  - pandas=1.0.3=py36h6c726b0_0
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.8.0=py36h9f0ad1d_1
  - pickleshare=0.7.5=py36h9f0ad1d_1001
  - pillow=7.1.2=py36h4655f20_0
  - pip=20.0.2=py36_3
  - pixman=0.38.0=h1de35cc_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - protobuf=3.11.4=py36h0130604_1
  - ptyprocess=0.6.0=py_1001
  - py-boost=1.67.0=py36h6440ff4_4
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyrsistent=0.16.0=py36h37b9a7d_0
  - pysocks=1.7.1=py36h9f0ad1d_1
  - python=3.6.10=hf48f09d_2
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2020.1=py_0
  - pyzmq=19.0.1=py36h820b253_0
  - rdkit=2020.03.2.0=py36h65625ec_1
  - readline=8.0=h1de35cc_0
  - requests=2.23.0=pyh8c360ce_2
  - scikit-learn=0.22.1=py36h27c97d8_0
  - scipy=1.4.1=py36h9fa6033_0
  - send2trash=1.5.0=py_0
  - setuptools=46.4.0=py36_0
  - six=1.14.0=py36_0
  - sqlite=3.31.1=h5c1f38d_1
  - tensorboard=1.8.0=py36_1
  - tensorflow=1.8.0=py36_1
  - termcolor=1.1.0=py_2
  - terminado=0.8.3=py36h9f0ad1d_1
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.4=py36h37b9a7d_1
  - traitlets=4.3.3=py36h9f0ad1d_1
  - urllib3=1.25.9=py_0
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.34.2=py36_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0

